buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

allprojects {
    group = 'vk.vkPets'
    version = '0.0.1'

    repositories {
        mavenLocal()
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'java-library'
    apply plugin: 'idea'

    configurations {
        qds
        compileClasspath.extendsFrom(qds)
    }

    dependencies {
//        qds ("com.devexperts.qd:dxfeed-api:${qdsVersion}")
        qds ("com.devexperts.qd:qds:${qdsVersion}")
        qds ("com.devexperts.qd:qds-monitoring:${qdsVersion}")
//        qds ("com.devexperts.qd:qds-file:${qdsVersion}")
        qds ("com.devexperts.qd:qds-tools:${qdsVersion}")

//    implementation files("../libs/${qdsVersion}/dxfeed-api-${qdsVersion}.jar")
//    implementation files("../libs/${qdsVersion}/dxlib-${qdsVersion}.jar")
//    implementation files("../libs/${qdsVersion}/mars-${qdsVersion}.jar")
//    implementation files("../libs/${qdsVersion}/qds-${qdsVersion}.jar")
//    implementation files("../libs/${qdsVersion}/qds-file-${qdsVersion}.jar")
//    implementation files("../libs/${qdsVersion}/qds-monitoring-${qdsVersion}.jar")
//    implementation files("../libs/${qdsVersion}/qds-tools-${qdsVersion}.jar")

        runtimeOnly "com.sun.jdmk:jmxtools:1.2.1"
        compileOnly 'org.jetbrains:annotations:19.0.0'
        testCompileOnly 'org.jetbrains:annotations:19.0.0'
    }

    tasks.register("deployQd", Copy) {
        doFirst {
            mkdir "../libs/${qdsVersion}"
        }

        into "../libs/${qdsVersion}"
        from configurations.qds

        doLast {
            def gitignoreFile = file("../libs/${qdsVersion}/.gitignore")
            gitignoreFile.text = "*"
        }
    }
}
