buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

configurations {
    qds
}

dependencies {
    qds "com.devexperts.qd:qds:${qdsVersion}"
    qds "com.devexperts.qd:qds-monitoring:${qdsVersion}"
    qds "com.devexperts.qd:qds-tools:${qdsVersion}"
}

tasks.register("deployQd", Copy) {
    def targetDir = file("./libs/${qdsVersion}")

    from(configurations.qds)
    into(targetDir)

    doLast {
        file("${targetDir}/.gitignore").text = "*"
    }
}


allprojects {
    apply plugin: 'java'
    apply plugin: 'java-library'
    apply plugin: 'idea'

    group = 'vk.vkPets'
    version = '0.0.1'

    repositories {
        mavenLocal()
        mavenCentral()
    }

    dependencies {
        api "com.devexperts.qd:qds:${qdsVersion}"
        api "com.devexperts.qd:qds-monitoring:${qdsVersion}"
        api "com.devexperts.qd:qds-tools:${qdsVersion}"
//        api ("com.devexperts.qd:qds-file:${qdsVersion}")
//        api ("com.devexperts.qd:dxfeed-api:${qdsVersion}")

//    implementation files("../libs/${qdsVersion}/dxfeed-api-${qdsVersion}.jar")
//    implementation files("../libs/${qdsVersion}/dxlib-${qdsVersion}.jar")
//    implementation files("../libs/${qdsVersion}/mars-${qdsVersion}.jar")
//    implementation files("../libs/${qdsVersion}/qds-${qdsVersion}.jar")
//    implementation files("../libs/${qdsVersion}/qds-file-${qdsVersion}.jar")
//    implementation files("../libs/${qdsVersion}/qds-monitoring-${qdsVersion}.jar")
//    implementation files("../libs/${qdsVersion}/qds-tools-${qdsVersion}.jar")

        runtimeOnly "com.sun.jdmk:jmxtools:1.2.1"
        compileOnly 'org.jetbrains:annotations:19.0.0'
        testCompileOnly 'org.jetbrains:annotations:19.0.0'
    }
}