#!/bin/bash

source ./qds-path.sh
CLASSPATH="$QDS_PATH;tools/build/libs/vk-qds-tools-0.0.1.jar;qdRmiMux/build/libs/qdRmiMux-0.0.1.jar"

# echo "using QDS_PATH: $QDS_PATH"
java -cp $CLASSPATH com.devexperts.qd.tools.Tools $@