#!/bin/bash

SCENARIO_FILE="$1"

if [[ ! -f "$SCENARIO_FILE" ]]; then
    echo "File not found: $SCENARIO_FILE"
    return 1
fi

# Symbol indicating the line should be joined with the next one
join_symbol="\\"
buffer=""

while IFS= read -r line || [[ -n "$line" ]]; do
    # Remove any trailing carriage return (CTRL-M)
    line="${line//$'\r'/}"

    # Skip empty lines and lines starting with #
    [[ -z "$line" || "$line" == \#* ]] && continue

    # Check if line ends with the join_symbol
    if [[ "$line" == *"$join_symbol" ]]; then
      # Remove the join_symbol and append line to buffer
      buffer+="${line%$join_symbol}"
    else
      # Append the line and Start the process in the background
      buffer+="$line"
#      echo "--> $buffer"
      eval "$buffer" &
      echo "Started: '$buffer' with PID $!"
      buffer=""
    fi
done < "$SCENARIO_FILE"

